theme = "tabi"
title = "> colton"

# The URL the site will be built for
base_url = "https://coltoneakins.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# default language
default_language = "en"

# taxonomies used for blog posts and projects
taxonomies = [{name = "tags", feed = true}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
seo_prefix = "Colton Eakins"
separator = "â€”"
skin = "teal"
homepage_seo_title = "Colton Eakins â€” Chicagoland Software Engineer"
stylesheets=['custom.css']
scripts=['custom.js']
menu = [
    { name = "projects", url = "projects", trailing_slash = false },
    { name = "blog", url = "blog", trailing_slash = false },
    { name = "contact", url = "contact", trailing_slash = false },
]
favicon = "/favicon.png"
favicon_emoji = "ğŸ‘¨â€ğŸ’»"
